version: '3'

services:
  prod:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/front
      - /front/node_modules
    ports:
      - "3000:3000"
    command: npm run build
