name: "CI"

on:
  pull_request:
    branches: ["master"]

jobs:
  test-back:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2 

    - name: Start test environment
      run: docker compose -f ./back/docker-compose.test.yml up -d --build --force-recreate --quiet-pull

    - name: Wait for tests to finish
      run: |
        while true; do
          sleep 2
          if [[ $(docker ps -a | grep Exited | grep api) ]]; then
            echo "Test Done!"
            break
          fi
        done

    - name: Display and analyse test results
      run: |
        result=$(docker logs ci-testing-test-api-1)
        echo "$result"
        if [[ "$result" == *"failing"* ]]; then
          echo "Tests have failed :/"
          exit 1
        else
          echo "All tests passed :)"
          exit 0
        fi